# author: Ole Schuett

timeout: 900s

substitutions:
  _IMAGE_NAME: "us-central1-docker.pkg.dev/${PROJECT_ID}/cp2kci/img_cp2kci_toolbox"

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["pull", "${_IMAGE_NAME}:latest"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "--cache-from", "${_IMAGE_NAME}:latest", "-t", "${_IMAGE_NAME}:${SHORT_SHA}", "./toolbox/"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_IMAGE_NAME}:${SHORT_SHA}"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "${_IMAGE_NAME}:${SHORT_SHA}", "${_IMAGE_NAME}:latest"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_IMAGE_NAME}:latest"]

#EOF
