# author: Ole Schuett

# Since GCP Build does not offer ARM machines we have to run on QEMU, which is slow.
timeout: "14400s"  # 4 hour

substitutions:
  _IMAGE_NAME: "us-central1-docker.pkg.dev/${PROJECT_ID}/cp2kci/img_cp2kci_toolbox_arm64"

steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'  # see https://github.com/GoogleCloudPlatform/cloud-builders/issues/253
  args: ["-c", "docker pull ${_IMAGE_NAME}:latest || exit 0"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["run", "--privileged", "multiarch/qemu-user-static", "--reset", "-p", "yes"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-f", "./toolbox/Dockerfile.arm64", "--platform", "linux/arm64", "--cache-from", "${_IMAGE_NAME}:latest", "-t", "${_IMAGE_NAME}:${SHORT_SHA}", "./toolbox/"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_IMAGE_NAME}:${SHORT_SHA}"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "${_IMAGE_NAME}:${SHORT_SHA}", "${_IMAGE_NAME}:latest"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_IMAGE_NAME}:latest"]

#EOF
