# author: Ole Schuett

substitutions:
  _IMAGE_NAME: "us-central1-docker.pkg.dev/${PROJECT_ID}/cp2kci/img_cp2kci_frontend"

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "${_IMAGE_NAME}:${SHORT_SHA}", "./frontend/"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_IMAGE_NAME}:${SHORT_SHA}"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "${_IMAGE_NAME}:${SHORT_SHA}", "${_IMAGE_NAME}:latest"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_IMAGE_NAME}:latest"]

- name: "gcr.io/cloud-builders/gcloud"
  args:
   - "run"
   - "deploy"
   - "cp2kci-frontend"
   - "--platform=managed"
   - "--region=us-central1"
   - "--image=${_IMAGE_NAME}:${SHORT_SHA}"

#EOF
