# author: Ole Schuett

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "img_cp2kci_backend", "./backend/"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "img_cp2kci_backend", "gcr.io/$PROJECT_ID/img_cp2kci_backend:$SHORT_SHA"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/img_cp2kci_backend:$SHORT_SHA"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "img_cp2kci_backend", "gcr.io/$PROJECT_ID/img_cp2kci_backend:latest"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/img_cp2kci_backend:latest"]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - cp2kci-backend-deployment
  - cp2kci-backend-container=gcr.io/$PROJECT_ID/img_cp2kci_backend:$SHORT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cp2k-cluster'
#EOF
