# author: Ole Schuett

substitutions:
  _IMAGE_NAME: "us-central1-docker.pkg.dev/${PROJECT_ID}/cp2kci/img_cp2kci_backend"

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["pull", "${_IMAGE_NAME}:latest"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "--cache-from", "${_IMAGE_NAME}:latest", "-t", "${_IMAGE_NAME}:${SHORT_SHA}", "./backend/"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_IMAGE_NAME}:${SHORT_SHA}"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "${_IMAGE_NAME}:${SHORT_SHA}", "${_IMAGE_NAME}:latest"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_IMAGE_NAME}:latest"]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - "set"
  - "image"
  - "deployment"
  - "cp2kci-backend-deployment"
  - "cp2kci-backend-container=${_IMAGE_NAME}:${SHORT_SHA}"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cp2k-cluster'
#EOF
