# author: Ole Schuett

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cp2kci-backend-k8s-account
automountServiceAccountToken: False

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cp2kci-backend-k8s-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cp2kci-backend-k8s-account
    namespace: default


#EOF
