# author: Ole Schuett

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cp2kci-janitor-cronjob
spec:
  schedule: "0  10  *  *  *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          automountServiceAccountToken: False
          serviceAccountName: cp2kci-cronjob-k8s-account
          dnsPolicy: Default
          nodeSelector:
            node.kubernetes.io/instance-type: n2d-standard-2
          containers:
          - name: cp2kci-janitor-cronjob-container
            image: "us-central1-docker.pkg.dev/cp2k-org-project/cp2kci/img_cp2kci_toolbox_x86:latest"
            command: ["/opt/cp2kci-toolbox/janitorial_duties.sh"]
            resources:
              requests:
                cpu: 1m

#EOF
